[package]
name = "debug-example"
version = "0.1.0"
edition = "2021"

[dependencies]
protobuf = "3.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
protobuf = "3.3"
protobuf-codegen = "3.3"
